"""Ingestion accuracy measurement (Phase 1 exit criterion).

The evaluation chapter is the graded part of the thesis, and the numbers in
``research/results/ingestion.md`` come from here — generated by script, never
typed by hand, because they will be re-run (doc 05, standing definition of done).

Matching is deliberately forgiving about *presentation* and strict about
*substance*: heading text is normalised (numbering and accents removed) before
comparison, but a heading at the wrong level still counts as a miss, because
level errors propagate into section ranges and the exclusion mask.
"""

from __future__ import annotations

import json
import re
import time
from collections import Counter
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

from app.models.ir import DocumentIR


@dataclass
class PrecisionRecall:
    tp: int = 0
    fp: int = 0
    fn: int = 0

    @property
    def precision(self) -> float:
        return round(self.tp / (self.tp + self.fp), 3) if self.tp + self.fp else 0.0

    @property
    def recall(self) -> float:
        return round(self.tp / (self.tp + self.fn), 3) if self.tp + self.fn else 0.0

    @property
    def f1(self) -> float:
        denominator = self.precision + self.recall
        return round(2 * self.precision * self.recall / denominator, 3) if denominator else 0.0

    def to_dict(self) -> dict[str, float]:
        return {
            "precision": self.precision,
            "recall": self.recall,
            "f1": self.f1,
            "tp": self.tp,
            "fp": self.fp,
            "fn": self.fn,
        }


def multiset_prf(predicted: list[str], expected: list[str]) -> PrecisionRecall:
    """Multiset precision/recall/F1 — order-insensitive, duplicates counted."""
    predicted_counts = Counter(predicted)
    expected_counts = Counter(expected)
    tp = sum(min(predicted_counts[key], expected_counts[key]) for key in expected_counts)
    fp = sum(predicted_counts.values()) - tp
    fn = sum(expected_counts.values()) - tp
    return PrecisionRecall(tp=tp, fp=fp, fn=fn)


@dataclass
class IngestionReport:
    document: str
    source_format: str
    headings: PrecisionRecall = field(default_factory=PrecisionRecall)
    sections: PrecisionRecall = field(default_factory=PrecisionRecall)
    citations: PrecisionRecall = field(default_factory=PrecisionRecall)
    references_expected: int = 0
    references_matched: int = 0
    figures_expected: int = 0
    figures_found: int = 0
    tables_expected: int = 0
    tables_found: int = 0
    code_blocks_expected: int = 0
    code_blocks_found: int = 0
    excluded_kinds_expected: list[str] = field(default_factory=list)
    excluded_kinds_found: list[str] = field(default_factory=list)
    blocks: int = 0
    pages: int = 0
    words: int = 0
    language_expected: str = ""
    language_found: str = ""
    language_correct: bool = False
    runtime_s: float = 0.0
    warnings: list[str] = field(default_factory=list)

    @property
    def reference_accuracy(self) -> float:
        if not self.references_expected:
            return 1.0
        return round(self.references_matched / self.references_expected, 3)

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["reference_accuracy"] = self.reference_accuracy
        return data


# -- normalisation ------------------------------------------------------------
_ACCENT_RE = re.compile(r"[^\w\s%.-]", re.UNICODE)


def normalise_text(text: str) -> str:
    """Lowercase, de-accent, drop numbering: ``2.1. Metodyka`` → ``metodyka``."""
    import unicodedata

    text = unicodedata.normalize("NFKD", text.strip().lower())
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    text = re.sub(r"^[\d\.\)\s]*(?:rozdzial|chapter)?[\s\d\.\)]*", "", text)
    text = _ACCENT_RE.sub(" ", text)
    return re.sub(r"\s+", " ", text).strip()


def heading_keys(ir: DocumentIR) -> list[str]:
    return [
        f"{normalise_text(b.text)}@{b.level or 0}"
        for b in ir.blocks
        if b.type == "heading" and b.text.strip()
    ]


def citation_keys(ir: DocumentIR) -> list[str]:
    """Comparable citation identities.

    LaTeX citations are matched on BibTeX keys (``\\cite{a,b}`` yields ``a``
    and ``b``); everything else is matched on the normalised raw form, which is
    what a reader of the report actually sees.
    """
    keys: list[str] = []
    for citation in ir.citations:
        if citation.style == "bibtex_key":
            keys.extend(
                normalise_text(key)
                for key in re.findall(r"\w[\w:-]*", citation.raw)
                if key != "cite"
            )
        else:
            keys.append(re.sub(r"\s+", "", citation.raw).lower())
    return keys


def _reference_matches(reference: Any, expectation: dict[str, Any]) -> bool:
    if "year" in expectation and reference.parsed.year != expectation["year"]:
        return False
    if "doi" in expectation and reference.parsed.doi != expectation["doi"]:
        return False
    if "first_author" in expectation:
        authors = " ".join(reference.parsed.authors).lower()
        if expectation["first_author"].lower() not in authors:
            return False
    return True


# -- evaluation ---------------------------------------------------------------
def evaluate(
    ir: DocumentIR, expected: dict[str, Any], *, document: str = "", runtime_s: float = 0.0
) -> IngestionReport:
    """Score one parsed document against its hand-written annotation."""
    report = IngestionReport(
        document=document or ir.source.filename,
        source_format=ir.source.format,
        blocks=len(ir.blocks),
        pages=ir.source.pages,
        words=ir.source.words,
        runtime_s=round(runtime_s, 3),
        warnings=[str(w) for w in ir.extra.get("parse_warnings", [])],
    )

    expected_headings = [
        f"{normalise_text(text)}@{int(level or 0)}" for text, level in expected.get("headings", [])
    ]
    report.headings = multiset_prf(heading_keys(ir), expected_headings)
    report.sections = multiset_prf(
        [s.kind for s in ir.sections], list(expected.get("sections", []))
    )

    expected_citations: list[str] = []
    for raw in expected.get("citations", []):
        if ir.source.format == "latex":
            expected_citations.append(normalise_text(raw))
        else:
            expected_citations.append(re.sub(r"\s+", "", raw).lower())
    report.citations = multiset_prf(citation_keys(ir), expected_citations)

    report.references_expected = len(expected.get("references", []))
    report.references_matched = sum(
        1
        for expectation in expected.get("references", [])
        if any(_reference_matches(ref, expectation) for ref in ir.references)
    )

    report.figures_expected = int(expected.get("figures", 0))
    report.figures_found = len(ir.figures)
    report.tables_expected = int(expected.get("tables", 0))
    report.tables_found = len(ir.tables)
    report.code_blocks_expected = int(expected.get("code_blocks", 0))
    report.code_blocks_found = sum(1 for b in ir.blocks if b.type == "code")

    report.excluded_kinds_expected = sorted(set(expected.get("excluded_kinds", [])))
    report.excluded_kinds_found = sorted({e.reason for e in ir.exclusion_mask})

    report.language_expected = str(expected.get("language", ""))
    report.language_found = ir.language.primary
    report.language_correct = report.language_found == report.language_expected
    return report


def time_parse(fn: Any) -> tuple[Any, float]:
    """Run *fn* and return ``(result, seconds)``."""
    started = time.perf_counter()
    result = fn()
    return result, time.perf_counter() - started


# -- aggregation --------------------------------------------------------------
def summarise(reports: list[IngestionReport]) -> dict[str, Any]:
    """Per-format roll-up for ``research/results/ingestion.md``."""
    by_format: dict[str, list[IngestionReport]] = {}
    for report in reports:
        by_format.setdefault(report.source_format, []).append(report)

    out: dict[str, Any] = {"documents": len(reports), "formats": {}}
    for fmt, group in sorted(by_format.items()):
        out["formats"][fmt] = {
            "documents": len(group),
            "heading_f1": round(_mean([r.headings.f1 for r in group]), 3),
            "heading_precision": round(_mean([r.headings.precision for r in group]), 3),
            "heading_recall": round(_mean([r.headings.recall for r in group]), 3),
            "section_f1": round(_mean([r.sections.f1 for r in group]), 3),
            "citation_f1": round(_mean([r.citations.f1 for r in group]), 3),
            "reference_accuracy": round(_mean([r.reference_accuracy for r in group]), 3),
            "language_accuracy": round(
                _mean([1.0 if r.language_correct else 0.0 for r in group]), 3
            ),
            "mean_runtime_s": round(_mean([r.runtime_s for r in group]), 3),
            "figure_recall": round(
                _mean(
                    [
                        (r.figures_found / r.figures_expected if r.figures_expected else 1.0)
                        for r in group
                    ]
                ),
                3,
            ),
            "table_recall": round(
                _mean(
                    [
                        (r.tables_found / r.tables_expected if r.tables_expected else 1.0)
                        for r in group
                    ]
                ),
                3,
            ),
        }
    return out


def _mean(values: list[float]) -> float:
    return sum(values) / len(values) if values else 0.0


def write_json(report_path: Path, reports: list[IngestionReport]) -> None:
    payload = {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "summary": summarise(reports),
        "documents": [report.to_dict() for report in reports],
    }
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
